#!/usr/bin/env bash
# This checks if an IP address is provided as an argument

# ip variable
ip_address="${1}"

# Get the filename of the script
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$ip_address" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${ip_address}"
fi
