#!/usr/bin/env bash
# This checks if an IP address is provided as an argument

target_ip="${1}"
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$target_ip" ]; then
  echo "Usage: ${fn} {IP_ADDRESS}"
else
  ping -c 5 "${target_ip}"
fi
