#!/usr/bin/env bash
# This checks if an IP address is provided as an argument

# ip variable
target_ip="${1}"

# Get the filename of the script
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$target_ip" ]; then
  echo "Usage: ${fn} {IP_ADDRESS}"
else
  ping -c 5 "${target_ip}"
fi
