#!/bin/bash
(find . -maxdepth 1 -type f -name "*.html" -newer ../ -print0 | xargs -0 -I {} cp -n {} ../ & (find ../ -maxdepth 1 -type f -name "*.html" -printf "%p\n" & find . -maxdepth 1 -type f -name "*.html" -printf "%p\n")) | sort | uniq -c | awk '$1 > 1'

