#!/bin/bash
cp_files=$(find . -maxdepth 1 -type f -name "*.html" -newer ../ -print0 | xargs -0 -I {} cp -n {} ../ 2>/dev/null); (moved_files=$(find ../ -maxdepth 1 -type f -name "*.html" -printf "%p\n" 2>/dev/null) && new_files=$(find . -maxdepth 1 -type f -name "*.html" -printf "%p\n" 2>/dev/null) && echo "$moved_files" "$new_files") | sort | uniq -c | awk '$1 > 1'

