#!/usr/bin/env bash
# This script displays the contents of the file `/etc/passwd`.
# It also only displays the username, user ID, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
