#!/usr/bin/env bash
# Fixing this container so that Nginx is running as user nginx

# Setting the user to run nginx as master process
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Configuring  the port binding to 8080
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default

# Giving permission to conf
chmod 644 /etc/nginx/nginx.conf

# Cnhanging the ownership of nginx server
chown nginx:nginx /etc/nginx/ -R

# Checking if running on port 8080
for pid in $(pidof apache2); do
    kill "$pid"
done
sudo -u nginx service nginx restart
